// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anboqzllfjdgtfciorcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuYm9xemxsZmpkZ3RmY2lvcmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODgzNzIsImV4cCI6MjA2MzY2NDM3Mn0.wZWnErUcuwsU-M_uzZ6_kpHgjj1oBK3nhfGBm44_Tes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);